---
common-steps:
  - &install_deps
    run:
      name: Install base dependencies for Debian python
      command: |
        set -e
        apt-get update && apt-get install -y sudo make git git-lfs gnupg python3 python3-venv
  - &install_packages
    run:
      name: Install packages
      command: |
        sudo apt install -y libnotify-bin

  - &run_tests
    run:
      name: Install test requirements and run tests
      command: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install --require-hashes -r requirements/dev-requirements.txt
        make check --keep-going

  - &install_packaging_dependencies
    run:
      name: Install Debian packaging dependencies and download wheels
      command: |
        mkdir ~/packaging && cd ~/packaging
        # local builds may not have an SSH url
        git config --global --unset url.ssh://git@github.com.insteadof || true
        git clone https://github.com/freedomofpress/securedrop-debian-packaging.git
        cd securedrop-debian-packaging
        make install-deps
        PKG_DIR=~/project make requirements

  - &verify_requirements
    run:
      name: Ensure that build-requirements.txt and requirements.txt are in sync.
      command: |
        cd ~/project
        # Return 1 if unstaged changes exist (after `make requirements` in the
        # previous run step), else return 0.
        git diff --quiet

  - &build_debian_package
    run:
      name: Build debian package
      command: |
        cd ~/packaging/securedrop-debian-packaging
        export PKG_VERSION=1000.0
        export PKG_PATH=~/project/
        make securedrop-export

  - &run_lint
    run:
      name: Install test requirements and run lint
      command: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install --require-hashes -r requirements/dev-requirements.txt
        make lint

  - &run_safety
    run:
      name: Check Python dependencies for CVEs
      command: |
        set -e
        source .venv/bin/activate
        make safety



version: 2
jobs:
  lint:
    docker:
      - image: debian:buster
    steps:
      - *install_deps
      - checkout
      - *run_lint
      - *run_safety

  lint-bullseye:
    docker:
      - image: debian:buster
    steps:
      - *install_deps
      - checkout
      - *run_lint
      - *run_safety

  test-buster:
    docker:
      - image: debian:buster
    steps:
      - *install_deps
      - checkout
      - *install_packages
      - *run_tests

  test-bullseye:
    docker:
      - image: debian:bullseye
    steps:
      - *install_deps
      - checkout
      - *install_packages
      - *run_tests

  build-buster:
    docker:
      - image: debian:buster
    steps:
      - *install_deps
      - checkout
      - *install_packaging_dependencies
      - *verify_requirements
      - *build_debian_package

  build-bullseye:
    docker:
      - image: debian:bullseye
    steps:
      - *install_deps
      - checkout
      - *install_packaging_dependencies
      - *verify_requirements
      - *build_debian_package


workflows:
  version: 2
  securedrop_export_ci:
    jobs:
      - lint
      - lint-bullseye
      - test-buster
      - test-bullseye
      - build-buster
      - build-bullseye
