---
common-steps:
  - &install_packages
    run:
      name: Install packages
      command: |
        sudo apt install libnotify-bin

  - &run_tests
    run:
      name: Install test requirements and run tests
      command: |
        virtualenv .venv
        source .venv/bin/activate
        pip install --require-hashes -r test-requirements.txt
        make test

version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: Install test requirements and run lint
          command: |
            virtualenv .venv
            source .venv/bin/activate
            pip install --require-hashes -r test-requirements.txt
            make lint
      - run:
          name: Check Python dependencies for CVEs
          command: |
            set -e
            source .venv/bin/activate
            make safety

  test-stretch:
    docker:
      - image: circleci/python:3.5-stretch
    steps:
      - checkout
      - *install_packages
      - *run_tests

  test-buster:
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - checkout
      - *install_packages
      - *run_tests

workflows:
  version: 2
  securedrop_export_ci:
    jobs:
      - lint
      - test-stretch
      - test-buster

